# Generated by Django 3.2.13 on 2022-05-11 15:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nemail_answer', '0005_auto_20220511_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='answer',
            new_name='topic',
        ),
    ]
